[tool.ruff]
line-length = 120
select = ["E", "F", "I", "UP"]
ignore = ["D203"]

[tool.ruff.isort]
known-local-folder = ["flaskapp"]

[tool.black]
line-length = 120

[tool.pytest.ini_options]
addopts = "-ra --cov -vv"

[tool.coverage.report]
show_missing = true